# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.cache/wt} [current_project]
set_property parent.project_path {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/repos/hardware-labs/Computer Sytem/Computer Sytem.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/init/mips_vga_dat.coe}}
add_files {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/init/mips_vga_code.coe}}
read_verilog -library xil_defaultlib {
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/RAM.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/ROM.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/processor/alu.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/processor/bru.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/processor/cpu.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/processor/cu.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/processor/regfile.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/vga.v}
  {E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/new/Computer.v}
}
read_ip -quiet {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory.xci}}
set_property used_in_implementation false [get_files -all {{e:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory_ooc.xdc}}]

read_ip -quiet {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Instruction_memory/Instruction_memory.xci}}
set_property used_in_implementation false [get_files -all {{e:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Instruction_memory/Instruction_memory_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/constrs_1/new/ees338vga.xdc}}
set_property used_in_implementation false [get_files {{E:/repos/hardware-labs/Computer Sytem/Computer Sytem.srcs/constrs_1/new/ees338vga.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Computer -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Computer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Computer_utilization_synth.rpt -pb Computer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
