# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/xhm2001/Desktop/senior1/hardware/hardware/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory.xci
# IP: The module: 'Data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xhm2001/Desktop/senior1/hardware/hardware/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/xhm2001/Desktop/senior1/hardware/hardware/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory.xci
# IP: The module: 'Data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xhm2001/Desktop/senior1/hardware/hardware/hardware-labs/Computer Sytem/Computer Sytem.srcs/sources_1/ip/Data_memory/Data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
